<script lang="ts">
	import { formatCompetition } from '$lib/competition.js';
	import Content from '$lib/components/Content.svelte';
	import { reportReasons } from '$lib/reports';
	import { testNames, type Test } from '$lib/tests.js';
	import Calculator from './Calculator.svelte';
	import Flag from '@lucide/svelte/icons/flag';
	import FlagOff from '@lucide/svelte/icons/flag-off';
	

	interface Props {
		question: any;
		onQuestionUpdate?: (updatedQuestion: any) => void;
	}

	let { question, onQuestionUpdate }: Props = $props();

	let showPage = $state(false);
	let revealAnswer = $state(false);

	async function requestAIExplanation() {
		const response = await fetch(`/api/v1/question/${question.$id}/request-ai-explanation`, {
			method: 'GET'
		});
		if (response.ok) {
			let data = await response.json();
			question.explanations.push(data.explanation);
			// Notify parent component of the update if callback is provided
			if (onQuestionUpdate) {
				onQuestionUpdate(question);
			}
		} else {
			alert('Failed to request AI explanation.');
		}
	}

	let showReportForm = $state(false);
</script>

{#if showPage}
	<div
		class="bg-opaque-100 fixed top-0 right-0 bottom-0 left-0 z-100 flex items-center justify-center"
	>
		<div class="max-h-full max-w-4xl overflow-y-auto rounded bg-white p-8 shadow-lg">
			<p class="text-lg">Question <strong>#{question.questionNumber}</strong></p>
			<button
				class="mb-4 rounded bg-red-600 px-4 py-2 text-white hover:bg-red-700"
				onclick={() => (showPage = false)}
			>
				Close
			</button>
			<img
				src="/api/v1/question/{question.$id}/page"
				alt="Full Question Page"
				class="h-auto w-full"
			/>
		</div>
	</div>
{/if}

<div class="flex flex-grow flex-col items-center justify-center overflow-y-auto p-4">
	<p class="text-gray-600 italic">
		From {formatCompetition(question.competition)} ({testNames[question.test as Test]} #{question.questionNumber})
	</p>
	<Content
		content={question.questionContent}
		class="question-content mx-auto max-w-4xl text-left text-xl"
	/>
	{#if question.includesDiagram}
		<p class="font-semibold">
			This question includes a diagram.
			<button class="underline" onclick={() => (showPage = true)}> See full page </button>
		</p>
	{:else}
		<p class="text-gray-600 italic">
			Having issues?
			<button class="underline" onclick={() => (showPage = true)}> See full page </button>
		</p>
	{/if}

	{#if revealAnswer}
		<div class="mt-8 max-h-1/2 w-full overflow-y-auto pt-4">
			<h2 class="mb-4 text-center text-lg font-semibold">Answer</h2>
			<Content
				content={question.answerContent}
				class="answer-content mx-auto max-w-4xl text-left text-xl"
			/>
			<h2 class="mt-8 mb-4 text-center text-lg font-semibold">Explanations</h2>
			{#each question.explanations as explanation}
				{#if explanation.aiGenerated}
					<p class="mb-4 rounded border bg-gray-50 p-4">
						This explanation was generated by AI and may not be accurate.
					</p>
				{/if}
				{#if explanation.textContent}
					<Content
						content={explanation.textContent}
						class="explanation-content mx-auto mb-6 max-h-1/2 max-w-4xl overflow-y-auto text-left text-lg"
					/>
				{/if}
				{#if explanation.image}
					<div class="explanation-image mb-6 flex justify-center">
						<img
							src={`/api/v1/explanations/${explanation.$id}`}
							alt="Explanation"
							class="h-auto max-w-full"
						/>
					</div>
				{/if}
			{/each}
			<button
				onclick={requestAIExplanation}
				class="mt-6 rounded bg-green-600 px-4 py-2 text-white hover:bg-green-700"
			>
				Request AI Explanation
			</button>
			<p>AI explanations may take a few moments to generate.</p>
		</div>
	{/if}

	<div class="mt-12 flex w-full justify-end gap-2">
		<button
			class="rounded bg-red-600 px-4 py-2 text-white hover:bg-red-700"
			onclick={() => (showReportForm = !showReportForm)}
			title={showReportForm ? 'Hide Report Form' : 'Report Question'}
		>
			{#if showReportForm}
				<FlagOff />
			{:else}
				<Flag />
			{/if}
		</button>
		<Calculator />
		{#if !revealAnswer}
			<button
				class="rounded bg-blue-600 px-4 py-2 text-white hover:bg-blue-700"
				onclick={() => (revealAnswer = true)}
			>
				Reveal Answer
			</button>
		{/if}
	</div>

	{#if showReportForm}
		<form class="mt-4" action={`/api/v1/question/${question.$id}/report`} method="POST">
			<label class="mb-2 block font-semibold"
				>Reason for Report:
				<select name="reason" class="mt-1 block w-full rounded border-gray-300 shadow-sm">
					{#each Object.entries(reportReasons) as [value, label]}
						<option {value}>{label}</option>
					{/each}
				</select>
			</label>
			<label class="mb-2 block font-semibold"
				>Additional Details (optional):
				<textarea
					name="details"
					rows="4"
					class="mt-1 w-full rounded border p-2"
					placeholder="Provide any additional information here..."
					maxlength="4096"
				></textarea>
				<p class="text-right text-sm text-gray-500">Max 4096 characters.</p>
			</label>
			<button type="submit" class="w-full rounded bg-red-600 px-4 py-2 text-white hover:bg-red-700">
				Submit Report
			</button>
		</form>
	{/if}
</div>
